### ISSUE TITLE
关于细节调整建议

### ISSUE THREAD

**Issue by marc-shen** [MosRat/MixTex-rs-GUI#3]
在经过简单测试后发现有以下问题：

1. 对大写英文字母的识别中，无法有效识别公式中的正体；
2. 英文字母O和数字0的之别准确度有待提高；
3. 希腊字母识别有误。

下两图为示例（上图为目标，下图为识别结果），注意其中的角标全部为正体，X和O均为大写英文字母，识别均有误。而小写英文字母角标的字体和内容识别均非常准确。

<img width="364" alt="截屏2024-08-25 10 46 35" src="https://github.com/user-attachments/assets/bdac90da-2b97-4477-b6ec-6f361ac6d9ae">

<img width="732" alt="截屏2024-08-25 10 52 45" src="https://github.com/user-attachments/assets/c8907427-c410-4635-84b0-ed81a240bc8d">

**Comment by MosRat** [comment]
![image](https://github.com/user-attachments/assets/6580317a-5092-4eb4-aa25-97da688191e3)
模型不是我训练的，我是做这个GUI和压缩量化模型，原作者模型结果就是上图[MixTex](https://mineai.top/)，我的结果和他一致。哥们你可以去[Mixtex](https://github.com/RQLuo/MixTeX-Latex-OCR/)提issue或者qq 612725068和作者交流，建议他进行相关微调

**Comment by MosRat** [comment]
好像上面网页版识别希腊字母是正确的，我分析了一下这个应该和预处理策略有关，原作者的离线版GUI MixTeX-v2.2.4和我的保持一致都错了，他和我用的是一样的方法填充图片，而他的网页版和我的网页版 https://mixtex.whl.moe/ 应该都是直接插值resize，结果都是识别正确
