### ISSUE TITLE
能否修改透明度

### ISSUE THREAD

**Issue by Jie-Qiao** [MosRat/MixTex-rs-GUI#8]
win10上的透明度设置似乎有点太过透明了

<img width="588" alt="_20241213144942" src="https://github.com/user-attachments/assets/490226a2-28cf-4725-889e-a83693853e09" />

**Comment by MosRat** [comment]
这是一个bug，我会修改来适配。透明是Windows11使用的mica特效在Windows10上缺失导致的，需要修改代码来检测系统版本以适配系统
![image](https://github.com/user-attachments/assets/54fb3ddb-baa4-40cb-aed8-ca0eb7ae81af)

**Comment by MosRat** [comment]
https://github.com/MosRat/MixTex-rs-GUI/releases/latest

**Comment by Jie-Qiao** [comment]
右键打开editor是不透明了，但是启动的界面还是全透明的。

直接打开：

<img width="609" alt="_20241215150217" src="https://github.com/user-attachments/assets/ccb451a5-7e82-49a2-a9f1-f24532f1f9bc" />

右键打开： 
<img width="625" alt="_20241215150245" src="https://github.com/user-attachments/assets/0d6f30ef-052d-4888-b75f-8abe70815d36" />

**Comment by MosRat** [comment]
尝试最新release，我没法复现上面情况
![result_3dview2](https://github.com/user-attachments/assets/a8b5556a-e494-44f5-b997-989aa357f5c7)

**Comment by Jie-Qiao** [comment]
试了最新的，已经可以了~~
